name: 'KMS SOPS Decrypt'
description: 'Decrypts files encrypted with SOPS using AWS KMS keys.'
author: 'iLife-Technologies'

# Define your inputs here.
inputs:
  kms-key-arn:
    description: 'KMS key ARN to be used for decryption'
    required: true
  input-file:
    description: 'Path to encrypted file'
    required: true

outputs:
  contents:
    description: 'Unencrypted contents of the input file'

runs:
  using: docker
  image: Dockerfile
  env:
    KMS_KEY_ARN: ${{ inputs.kms-key-arn }}
    INPUT_FILE: ${{ inputs.input-file }}
    OUTPUT_FILE: ${{ inputs.output-file }}
